### PR TITLE
Update registry.json

### PR DESCRIPTION
**Pull request by matrix2113**
I made an uptime command but it’s kinda useless. Papier helped me fix it.

### CODE REVIEW

**Comment by fourjr** [comment]
What's the propose of this plugin? As you mentioned, it is already possible for the same functionality to be done via the `about` command.

**Comment by matrix2113** [comment]
@fourjr so you only need to see the uptime instead of everything else (ping, etc links)

**Comment by fourjr** [comment]
@kyb3r im voting a no

**Comment by kyb3r** [comment]
There's no use for this plugin

**Pull request closed without merging**
