### PR TITLE
Update recipient_thread_close config help

### PR DESCRIPTION
**Pull request by StephenDaDev**
I have more I would like to add over the next week-week and a half

### CODE REVIEW

**Comment by Taaku18** [comment]
Whatcha gonna add? hmm 🤔

**Comment by StephenDaDev** [comment]
Waiting for other PRs to merge, as some of it is based on that

**Comment by StephenDaDev** [comment]
Ok My current set of things I want to add (maybe in this PR maybe not)

- [ ] Ability to disable ``mention`` 
- [ ] All my other ideas are bad, I will update if/when needed

1. I know how to do it just need to add

**Comment by StephenDaDev** [comment]
Forget it, Took so long that what I was gonna do was already made by someone else. Just gonna PR what I got with config help

**Comment by StephenDaDev** [comment]
😃

**Pull request merged**
