### PR TITLE
Add rules plugin to registry

### PR DESCRIPTION
**Pull request by StephenDaDev**
The title says all of it but, Hello.

### CODE REVIEW

**Comment by officialpiyush** [comment]
Oh oh oh StephenDaDev into plugins woooooooooooooooo

**Comment by StephenDaDev** [comment]
lol

**Comment by DAzVise** [comment]
use cases? i think modmail's use case is for big servers which probably already have a set of rules.

**Comment by officialpiyush** [comment]
Seems like tough competition ahead 🕵️‍♀️

**Comment by officialpiyush** [comment]
@DazVise i guess you forgot, modmail is used by servers having > 10 members too 😂🙄

**Comment by DAzVise** [comment]
@officialpiyush so do you think this plugin should get added to the plugins registry? not to be rudebut it's just text which should not be part of a bot's functionality

**Comment by StephenDaDev** [comment]
Some people, the first thing they do is deploy a Modmail, this could also assist with helping them get their server ready faster, and will just serve a starter for them to change their rules as needed, (Also for lazy ppl like piyush)

**Comment by StephenDaDev** [comment]
(that sounded kinda mean, I wasn't trying to insult piyush)

**Comment by officialpiyush** [comment]
Yes I'm lazy kiddo 😁🤧

**Comment by Akhil2149** [comment]
Not fancy. Embedder plugin or announcement plugin can already do this.

**Pull request closed without merging**
