### PR TITLE
Add space before "was created ..."

### PR DESCRIPTION
**Pull request by xPolar**
Currently when a new thread is created it shows "@MENTIONwas" created because you have a list of information that you just add onto the embed description with a join. However the first item in a list does not get a separator and does have a space before being added to the embed description. Adding a space in the was created will fix this issue.

Image

### CODE REVIEW

**Comment by RealCyGuy** [comment]
wow i didn't even notice that lol

**Review by fourjr — CHANGES_REQUESTED** [review]
This PR contains changes advertising your server?

Thanks for noticing the typo though, will amend manually.

**Comment by xPolar** [comment]
> This PR contains changes advertising your server?
> 
> Thanks for noticing the typo though, will amend manually.

All I did was add the space, looks like others added different commits for some reason?

**Comment by fourjr** [comment]
Oh, sorry. I misread the commits.

**Pull request closed without merging**
