### PR TITLE
Add audit log to Modmail

### PR DESCRIPTION
**Pull request by StephenDaDev**
Adding a Audit Log to modmail

ie. "Stephen#2806 has opened a thread for Matrix#2113"

### CODE REVIEW

**Comment by matrix2113** [comment]
hey its me ;0

**Comment by StephenDaDev** [comment]
Change in plans, only doing for major operations, not useless stuff like contact command. Also got my laptop back from Apple so I'm going to start working on this tonight

**Comment by officialpiyush** [comment]
Marjor operations like perms add and stuff?

**Comment by StephenDaDev** [comment]
Yes, Exactly

**Comment by officialpiyush** [comment]
How is this going?

**Comment by TheKinG2149** [comment]
👀 oh Stephen is doing this

**Pull request closed without merging**
