### PR TITLE
Updating bot

### PR DESCRIPTION
**Pull request by Fantom-XR**

### CODE REVIEW

**Comment by Fantom-XR** [comment]
finally

**Comment by lorenzo132** [comment]
@Fantom-XR This is not how you update your bot, follow this tutorial > https://github.com/kyb3r/modmail/wiki/updating

**Comment by Fantom-XR** [comment]
> @Fantom-XR This is not how you update your bot, follow this tutorial > https://github.com/kyb3r/modmail/wiki/updating

@lorenzo132 I am using heroku.

**Comment by lorenzo132** [comment]
Correct, but now you want to edit the main repo of modmail. simply redeploy your bot using this template > https://dashboard.heroku.com/new?template=https://github.com/kyb3r/modmail <
Use the same info which you already have in your old app, which can be found here > https://i.imgur.com/L2jNfOt.png <

**Comment by lorenzo132** [comment]
This PR can be closed @fourjr

**Pull request closed without merging**
