### PR TITLE
Fix Plugins don't being updated if we force push on plugins repo

### PR DESCRIPTION
**Pull request by officialpiyush**
# What's This?

* While testing my plugin, I came over this situation many times, so, I made a pr to fix it.

* In this pr, I used the `-f` flag to force update the plugins repo.

# Image Of Error

image

### CODE REVIEW

**Comment by officialpiyush** [comment]
Oh nvm

**Comment by officialpiyush** [comment]
# Don't Merge until I test again

**Comment by officialpiyush** [comment]
# It Works!

image

**Comment by officialpiyush** [comment]
# Output after `get fetch --all`

image

**Comment by fourjr** [comment]
Ready for merge?

**Comment by officialpiyush** [comment]
yes

**Pull request merged**
