### PR TITLE
Update registry.json

### PR DESCRIPTION
**Pull request by NroxpTheDev**

### CODE REVIEW

**Review by fourjr — CHANGES_REQUESTED** [review]
My comment from #3026 still stands. There is no point creating a new PR.
> Configuration keys should be editable through commands using a database partition. There should be no config keys hardcoded into plugin's code.

**Comment by NroxpTheDev** [comment]
PR Has Been Closed

**Comment by StephenDaDev** [comment]
Except it hasn't.

**Comment by lorenzo132** [comment]
Ola @NroxpTheDev , this will be the last time we will mention this feature wont be added. Please do not make any new githubissues for this.

**Pull request closed without merging**
