### PR TITLE
Add run on repl.it badge to README

### PR DESCRIPTION
**Pull request by RobloxStreetMagic**
This pull request adds a  badge to the . This will allow users to easily run this repository in their browser, without having to set up an environment. You can learn more about Repl.it [here](https://repl.it).

### CODE REVIEW

**Comment by RealCyGuy** [comment]
I don't think this is necessary.

**Comment by fadedmax** [comment]
It will work, the readme part can go tho, it doesnt need to be at the very top.
it might be a good edition tho, i just dont think repi.it is very widley used since its public

**Comment by ririko5834** [comment]
Good idea

**Comment by fourjr** [comment]
Hey, officially we do not plan to support repl.it yet due to its disadvantage of "requiring a ping every 30 minutes". We might look at this again in the future though.

**Pull request closed without merging**
