### PR TITLE
Add Debug Plugin To Registry

### PR DESCRIPTION
**Pull request by MiTonder**

### CODE REVIEW

**Comment by MiTonder** [comment]
Should i er add tags? Piyush says its worling fine.

**Comment by iamluca** [comment]
@StephenDaDev @MiTonder 

Good afternoon,

Just checking out this pull request and it seems that the Travis CI pull request checker that runs the code to make sure that the bot works before we release it to the public errored.

Below is the attached code that errored:

```fix
$ git clone --depth=50 https://github.com/kyb3r/modmail.git kyb3r/modmail
Cloning into 'kyb3r/modmail'...
remote: Enumerating objects: 266, done.
remote: Counting objects: 100% (266/266), done.
remote: Compressing objects: 100% (146/146), done.
remote: Total 266 (delta 149), reused 208 (delta 116), pack-reused 0
Receiving objects: 100% (266/266), 143.46 KiB | 3.78 MiB/s, done.
Resolving deltas: 100% (149/149), done.
$ cd kyb3r/modmail
$ git fetch origin +refs/pull/292/merge:
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 13 (delta 6), reused 8 (delta 2), pack-reused 0
Unpacking objects: 100% (13/13), done.
From https://github.com/kyb3r/modmail
 * branch            refs/pull/292/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
$ source ~/virtualenv/python3.7/bin/activate
$ python --version
Python 3.7.1
$ pip --version
pip 19.0.3 from /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pip (python 3.7)
$ pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
The command "pip install -r requirements.txt" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by fourjr** [comment]
@iamluca That is a problem in our side. Not this pr.

**Comment by StephenDaDev** [comment]
> @iamluca That is a problem in our side. Not this pr.

I myself knew, its been doing that for weeks.

**Comment by MiTonder** [comment]
YEES

**Comment by kyb3r** [comment]
bad plugin idea, closing.

**Pull request closed without merging**
