### PR TITLE
Add a "no command description" in the help command.

### PR DESCRIPTION
**Pull request by Vincysuper07**
This should work, for example, when someone tries to see the Moderation plugin. Commands in that plugin have no description, so it will show "No description." instead of nothing.

### CODE REVIEW

**Comment by fourjr** [comment]
Your PR should not be changing the code style outside of the main PR reason

**Comment by Vincysuper07** [comment]
I know, but the code-style thing was failing, so I thought to reformat the code...

**Comment by fourjr** [comment]
Run `black` to fix the styling

**Comment by Vincysuper07** [comment]
That's what I did.

**Review by fourjr — APPROVED** [review]

**Pull request merged**
