### PR TITLE
Discordpy bump

### PR DESCRIPTION
**Pull request by Taaku18**
Bump to latest dpy version.

### CODE REVIEW

**Comment by RheaAyase** [comment]
What a giant chaos of commits. Please create self contained commits. Use `git rebase -i HEAD~n` where `n` is the number of commits you want to review. Then follow instructions in the interactive rebase.

**Comment by RheaAyase** [comment]
...while I'm at it, what does `Discord.py bump` have to do with "Deprecated `MONGO_URI`" and all the other changes in this pull request?

**Comment by lorenzo132** [comment]
Hey there @RheaAyase ,
We truly apprectiate you'r cooperation, But it seems like you only are complaining and complaning. Please Keep in mind we try to do what we can, in a messy way or not the result will be fine as it always has been.
Cheers lorenzo,

**Comment by RheaAyase** [comment]
I'm not complaining. I'm pointing out these issues so that you can learn from these mistakes. Not everyone is born all cute and nice. Yes I do appreciate your work, but do I have to pre-face every single online message? I prefer getting to the point without wasting anyones time.

**Comment by RheaAyase** [comment]
These things that I'm describing matter a lot in the open source. 

This is what a complaint looks like: I now have to either deal with all this chaos in order to merge it with my fork, or I'll live with the divergence. In my case it's the latter, with a single cherry-picked commit out of this pull request. The rest is not worth the hassle.

**Comment by lorenzo132** [comment]
Hey,

I fully agree with the fact that these things matter, specially with a open-source project. Although You also will have to understand also we live in a big chaos to keep all you guys happy > to keep the quality of the end product as high as possible, we dont focus fully on how a simple "commit" looks like. And if you think different, Please and be my guest and create your own open-source bot, and then show me how it should be.

Cheers, lorenzo

**Comment by RheaAyase** [comment]
> Please and be my guest and create your own open-source bot

I have, several in fact. And they all actually work and I can just let em do their thing for months at a time and it doesn't die on me on every occasion.

Yours is unreliable, and with development that I've observed not only in this pull request, yes I'll be rather writing my own as it will be less time, effort and headaches, than fixing all this mess. You will see mine pop up at https://github.com/RheaAyase/Valkyrja.modmail by the end of the day.

**Comment by lorenzo132** [comment]
I'll be waiting👍,  And if you only have issues and issues. Feel free to continue to use any other `project`, and have your complaints somewhere else.
Cheers, lorenzo

**Comment by RheaAyase** [comment]
Again, you see complaints, while the fact is that I tried to help you. This pull request is a nightmare and anyone can clearly see that.

**Pull request merged**
