### PR TITLE
make approved issues not stale

### PR DESCRIPTION
**Pull request by RealCyGuy**

### CODE REVIEW

**Comment by StephenDaDev** [comment]
What do you think about adding the labels "bug" as well as "maybe:bug"

**Comment by RealCyGuy** [comment]
maybe not maybe: bug

**Comment by StephenDaDev** [comment]
Yeah, I'd have to agree with that within 100 days, it should be decided

**Comment by Coolguy3289** [comment]
Any reason why this hasn't been merged yet?

**Pull request merged**
